const details= [
    {
        id : 1,
        matNO : 'FSC/CSC/001',
        name: 'Oghenekaro Emmanuella',
        testScore : 27,
        examScore : 50,
        remark: 'Very Good',
    },
    {
        id : 2,
        matNO : 'FSC/CSC/010',
        name: 'Cody Fisher',
        testScore : 24,
        examScore : 60,
        remark: 'Very Good',
    },
    {
        id : 3,
        matNO : 'FSC/CSC/011',
        name: 'Jenny Wilson',
        testScore : 14,
        examScore : 30,
        remark: 'Very Good',
    },
    {
        id : 4,
        matNO : 'FSC/CSC/012',
        name: 'Kristin Watson',
        testScore : 30,
        examScore : 45,
        remark: 'Very Good',
    },
    {
        id : 5,
        matNO : 'FSC/CSC/013',
        name: 'Esther Howard',
        testScore : 11,
        examScore : 20,
        remark: 'Very Good',
    },
    {
        id : 6,
        matNO : 'FSC/CSC/014',
        name: 'Darlene Robertson',
        testScore : 19,
        examScore : 10,
        remark: 'Very Good',
    },
    {
        id : 7,
        matNO : 'FSC/CSC/015',
        name: 'Robert Fox',
        testScore : 24,
        examScore : 40,
        remark: 'Very Good',
    },
    {
        id : 8,
        matNO : 'FSC/CSC/016',
        name: 'Eleanor Pena',
        testScore : 26,
        examScore : 60,
        remark: 'Very Good',
    },
    {
        id : 9,
        matNO : 'FSC/CSC/017',
        name: 'Leslie Alexander',
        testScore : 22,
        examScore : 20,
        remark: 'Very Good',
    },
    {
        id : 10,
        matNO : 'FSC/CSC/018',
        name: 'Floyd Miles',
        testScore : 16,
        examScore : 8,
        remark: 'Very Good',
    },
    {
        id : 11,
        matNO : 'FSC/CSC/019',
        name: 'Brooklyn Simmons',
        testScore : 12,
        examScore : 50,
        remark: 'Very Good',
    },
    {
        id : 12,
        matNO : 'FSC/CSC/020',
        name: 'Marvin McKinney',
        testScore : 21,
        examScore : 35,
        remark: 'Very Good',
    },
    {
        id : 13,
        matNO : 'FSC/CSC/021',
        name: 'Devon Lane',
        testScore : 4,
        examScore : 28,
        remark: 'Very Good',
    },
    {
        id : 14,
        matNO : 'FSC/CSC/022',
        name: 'Jane Cooper',
        testScore : 14,
        examScore : 60,
        remark: 'Very Good',
    },{
        id : 15,
        matNO : 'FSC/CSC/023',
        name: 'Guy Hawkins',
        testScore : 24,
        examScore : 54,
        remark: 'Very Good',
    },
    
    
]
export default details